image: ubuntu:20.04

variables:
  GIT_DEPTH: 0

stages:
  - container
  - debug
  - compile

container:
  stage: container
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/.gitlab-ci-dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  when: manual

debug:
  image:
    name: "ubuntu:20.04"
  stage: debug
  script:
    - bash .gitlab-ci-setup.sh
    - bash .gitlab-ci-compile.sh
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  when: manual

compile:
  image:
    name: "$CI_REGISTRY_IMAGE:latest"
  stage: compile
  script:
    - bash .gitlab-ci-compile.sh
  artifacts:
    paths:
      - build/
    expire_in: 1 week